// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfENTVCNfmtkjUVBRlUN25beN4oT4gDII',
    appId: '1:282937028069:web:cc2da7ae6e16fc4b5f530c',
    messagingSenderId: '282937028069',
    projectId: 'feastfriends-78d6d',
    authDomain: 'feastfriends-78d6d.firebaseapp.com',
    storageBucket: 'feastfriends-78d6d.appspot.com',
    measurementId: 'G-3G38VY1JT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABXATP-sa3zyw1poPnpXht0cH_m3WUUdc',
    appId: '1:282937028069:android:0a199eb8bf5cad375f530c',
    messagingSenderId: '282937028069',
    projectId: 'feastfriends-78d6d',
    storageBucket: 'feastfriends-78d6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1PiH7vq9D-bZ5G8gEilfpIMZMrhfGH1U',
    appId: '1:282937028069:ios:82eba1667f84bfbf5f530c',
    messagingSenderId: '282937028069',
    projectId: 'feastfriends-78d6d',
    storageBucket: 'feastfriends-78d6d.appspot.com',
    iosBundleId: 'com.example.feastFriends',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1PiH7vq9D-bZ5G8gEilfpIMZMrhfGH1U',
    appId: '1:282937028069:ios:82eba1667f84bfbf5f530c',
    messagingSenderId: '282937028069',
    projectId: 'feastfriends-78d6d',
    storageBucket: 'feastfriends-78d6d.appspot.com',
    iosBundleId: 'com.example.feastFriends',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfENTVCNfmtkjUVBRlUN25beN4oT4gDII',
    appId: '1:282937028069:web:99b920fa308c53c25f530c',
    messagingSenderId: '282937028069',
    projectId: 'feastfriends-78d6d',
    authDomain: 'feastfriends-78d6d.firebaseapp.com',
    storageBucket: 'feastfriends-78d6d.appspot.com',
    measurementId: 'G-CGTKMVCCGT',
  );

}