// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbBMTG4l9cXQAQgNznctcBsUdgRjPtIXI',
    appId: '1:182471678371:web:575cd0765d1650207fa216',
    messagingSenderId: '182471678371',
    projectId: 'feastfriends-6a21c',
    authDomain: 'feastfriends-6a21c.firebaseapp.com',
    databaseURL: 'https://feastfriends-6a21c-default-rtdb.firebaseio.com',
    storageBucket: 'feastfriends-6a21c.appspot.com',
    measurementId: 'G-MYXCFXQTMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIbtEnmVYEcGU5KPuP8RUrl3shwn8gqAI',
    appId: '1:182471678371:android:c8b3eaa3a1a29ff67fa216',
    messagingSenderId: '182471678371',
    projectId: 'feastfriends-6a21c',
    databaseURL: 'https://feastfriends-6a21c-default-rtdb.firebaseio.com',
    storageBucket: 'feastfriends-6a21c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCACcBKwMUsESGAs5vFcb3yoy0eERmeZg8',
    appId: '1:182471678371:ios:3f3ba83ed8b461df7fa216',
    messagingSenderId: '182471678371',
    projectId: 'feastfriends-6a21c',
    databaseURL: 'https://feastfriends-6a21c-default-rtdb.firebaseio.com',
    storageBucket: 'feastfriends-6a21c.appspot.com',
    iosBundleId: 'com.example.feastFriends',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCACcBKwMUsESGAs5vFcb3yoy0eERmeZg8',
    appId: '1:182471678371:ios:3f3ba83ed8b461df7fa216',
    messagingSenderId: '182471678371',
    projectId: 'feastfriends-6a21c',
    databaseURL: 'https://feastfriends-6a21c-default-rtdb.firebaseio.com',
    storageBucket: 'feastfriends-6a21c.appspot.com',
    iosBundleId: 'com.example.feastFriends',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbBMTG4l9cXQAQgNznctcBsUdgRjPtIXI',
    appId: '1:182471678371:web:dbb7fafaa29e5ab47fa216',
    messagingSenderId: '182471678371',
    projectId: 'feastfriends-6a21c',
    authDomain: 'feastfriends-6a21c.firebaseapp.com',
    databaseURL: 'https://feastfriends-6a21c-default-rtdb.firebaseio.com',
    storageBucket: 'feastfriends-6a21c.appspot.com',
    measurementId: 'G-W2FRW9H9S3',
  );
}
