// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAQjdMzyQtYdyZsnEmVAIl1HtDjhbS-5g',
    appId: '1:239449676856:web:aa35e7839cd6d9589edacd',
    messagingSenderId: '239449676856',
    projectId: 'feastfriends-38e58',
    authDomain: 'feastfriends-38e58.firebaseapp.com',
    databaseURL: 'https://feastfriends-38e58-default-rtdb.firebaseio.com',
    storageBucket: 'feastfriends-38e58.appspot.com',
    measurementId: 'G-LR94ZGV3XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDth3JNGmM0B-e2BD2CcmfCBlFa9CQnI4M',
    appId: '1:239449676856:android:6ee0acd8a6c6fbc99edacd',
    messagingSenderId: '239449676856',
    projectId: 'feastfriends-38e58',
    databaseURL: 'https://feastfriends-38e58-default-rtdb.firebaseio.com',
    storageBucket: 'feastfriends-38e58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjpz6PoXZ0rU5KONf676WVzdv7YDJgBLM',
    appId: '1:239449676856:ios:474a547d4ed448dd9edacd',
    messagingSenderId: '239449676856',
    projectId: 'feastfriends-38e58',
    databaseURL: 'https://feastfriends-38e58-default-rtdb.firebaseio.com',
    storageBucket: 'feastfriends-38e58.appspot.com',
    iosBundleId: 'com.example.feastFriends',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjpz6PoXZ0rU5KONf676WVzdv7YDJgBLM',
    appId: '1:239449676856:ios:474a547d4ed448dd9edacd',
    messagingSenderId: '239449676856',
    projectId: 'feastfriends-38e58',
    databaseURL: 'https://feastfriends-38e58-default-rtdb.firebaseio.com',
    storageBucket: 'feastfriends-38e58.appspot.com',
    iosBundleId: 'com.example.feastFriends',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAQjdMzyQtYdyZsnEmVAIl1HtDjhbS-5g',
    appId: '1:239449676856:web:eeb809f41d1e4c589edacd',
    messagingSenderId: '239449676856',
    projectId: 'feastfriends-38e58',
    authDomain: 'feastfriends-38e58.firebaseapp.com',
    databaseURL: 'https://feastfriends-38e58-default-rtdb.firebaseio.com',
    storageBucket: 'feastfriends-38e58.appspot.com',
    measurementId: 'G-P2EJQ4E1CQ',
  );
}
